// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace fcmd
{
    
    #region Windows Form Designer generated code
    public partial class frmMain
    {
        private void InitializeComponent()
        {
            this.mstMenu = new System.Windows.Forms.MenuStrip();
            this.mstKeyboard = new System.Windows.Forms.MenuStrip();
            // 
            // mstMenu
            // 
            this.mstMenu.Name = "mstMenu";
            this.mstMenu.TabIndex = 0;
            this.mstMenu.DefaultDropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.BelowRight;
            this.mstMenu.RenderMode = System.Windows.Forms.ToolStripRenderMode.ManagerRenderMode;
            this.mstMenu.GripMargin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.mstMenu.LayoutStyle = System.Windows.Forms.ToolStripLayoutStyle.HorizontalStackWithOverflow;
            this.mstMenu.Size = new System.Drawing.Size(599, 24);
            this.mstMenu.Text = "mstMenu";
            this.mstMenu.ImageScalingSize = new System.Drawing.Size(16, 16);
            this.mstMenu.ItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.mstMenu_ItemClicked);
            // 
            // mstKeyboard
            // 
            this.mstKeyboard.Name = "mstKeyboard";
            this.mstKeyboard.TabIndex = 1;
            this.mstKeyboard.DefaultDropDownDirection = System.Windows.Forms.ToolStripDropDownDirection.BelowRight;
            this.mstKeyboard.RenderMode = System.Windows.Forms.ToolStripRenderMode.ManagerRenderMode;
            this.mstKeyboard.GripMargin = new System.Windows.Forms.Padding(2, 2, 0, 2);
            this.mstKeyboard.LayoutStyle = System.Windows.Forms.ToolStripLayoutStyle.HorizontalStackWithOverflow;
            this.mstKeyboard.Location = new System.Drawing.Point(0, 289);
            this.mstKeyboard.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.mstKeyboard.Size = new System.Drawing.Size(599, 24);
            this.mstKeyboard.Text = "menuStrip2";
            this.mstKeyboard.ImageScalingSize = new System.Drawing.Size(16, 16);
            // 
            // frmMain
            // 
            this.Name = "frmMain";
            this.ClientSize = new System.Drawing.Size(599, 305);
            this.Controls.Add(this.mstMenu);
            this.Controls.Add(this.mstKeyboard);
            this.Text = "File Commander";
			this.KeyPreview = true;
            this.Resize += new System.EventHandler(this.frmMain_Resize);
            this.Load += new System.EventHandler(this.frmMain_Load);
        }
        private System.Windows.Forms.MenuStrip mstMenu;
        private System.Windows.Forms.MenuStrip mstKeyboard;
    }
    #endregion
}
