/* The File Commander
 * Интерфейс главного окна
 * (C) 2013, Alexander Tauenis (atauenis@yandex.ru)
 * Копирование кода разрешается только с письменного согласия
 * разработчика (А.Т.).
 */
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace fcmd
{
    
    #region Windows Form Designer generated code
    public partial class frmMain
    {

        private void InitializeComponent()
        {
            this.SuspendLayout();
            // 
            // frmMain
            // 
            this.ClientSize = new System.Drawing.Size(599, 305); 
            this.Name = "frmMain";
            this.Text = "File Commander";
            this.Load += new System.EventHandler(this.frmMain_Load);
            this.ResumeLayout(false);

            // 
            // listPanel1
            // 
            this.listPanel1 = new fcmd.ListPanel();
            this.listPanel1.Location = new System.Drawing.Point(0, 30);
            this.listPanel1.Name = "listPanel1";
            this.listPanel1.Size = new System.Drawing.Size(300, 300);
            this.listPanel1.BackColor = System.Drawing.Color.FromName("yellow");
            this.listPanel1.TabIndex = 0;
            this.listPanel1.DoubleClick += new System.EventHandler(this.Panel_DblClick);
            this.Controls.Add(this.listPanel1);

        }

    }
    #endregion
}
